<?php

namespace ChiTiet;
require_once "ChiTiet.php";

class  ChiTietDon extends ChiTiet
{
    private $giaTien;
    private $khoiLuong;

    public function nhapThongTin()
    {
        parent::nhapThongTin(); // TODO: Change the autogenerated stub
        do {
            $this->khoiLuong = readline("Khoi luong: ");
            if (!is_numeric($this->khoiLuong)) {
                echo $this->khoiLuong . " is not numberic!\n";
            }
        } while (!is_numeric($this->khoiLuong));
        do {
            $this->giaTien = readline("Gia tien: ");
            if (!is_numeric($this->giaTien)) {
                echo $this->giaTien . " is not numberic!\n";
            }
        } while (!is_numeric($this->giaTien));
    }


    public function xuatThongTin($level)
    {
        $tab_string = $this->makeLevelTab($level);
        echo $tab_string . "[CTD]\n";
        parent::xuatThongTin($level); // TODO: Change the autogenerated stub
        echo "\n";
        echo $tab_string . "Khoi Luong: " . $this->khoiLuong . "(kg)\n" ;
        echo $tab_string . "Gia: " . $this->giaTien . "$\n";

    }


    public function getGiaTien()
    {
        return $this->giaTien;
    }

    public function getKhoiLuong()
    {
        return $this->khoiLuong;
    }

}



